name: hackfest_signmate
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  screen_utils: ^0.0.1
  hexcolor: ^3.0.1
  flutter_screenutil: ^5.6.1
  firebase_core: ^2.7.0
  speech_to_text: ^6.1.1
  avatar_glow: ^2.0.2
  cloud_firestore: ^4.4.3
  url_launcher: ^6.1.10

  camera: ^0.10.0+4
  path: ^1.8.2
  path_provider: ^2.0.11
  google_mlkit_object_detection: ^0.6.0
  image_picker: ^0.8.6+4

  firebase_auth: ^4.2.9
  flutter_facebook_auth: ^5.0.7
  google_sign_in: ^6.0.1
  firebase_storage: ^11.0.14


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/categories/
    - assets/images/social/
    - assets/images/feature/

    - assets/ml/

    - assets/images/place_categories/


  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
