name: hackfest_signmate
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  screen_utils: ^0.0.1
  hexcolor: ^3.0.1
  flutter_screenutil: ^5.6.1
  firebase_core: ^2.7.0
  speech_to_text: ^6.1.1
  avatar_glow: ^2.0.2
  cloud_firestore: ^4.4.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/categories/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
